server:
  port: 9081


spring:
# conifiguration database
  datasource:
    url: jdbc:h2:mem:authdb           # In-memory DB (data lost on restart)
    driver-class-name: org.h2.Driver
    username: admin                     # Default H2 username
    password: admin              # Default H2 password (empty)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update                # Auto create/update tables
    show-sql: true                    # Show SQL in logs (DEV only)
    properties:
      hibernate:
        format_sql: true  # frmate sql querys
    open-in-view: false
  h2:
    console:
      enabled: true                   # Enables H2 web console
      path: /h2-console               # Access at http://localhost:9081/h2-console
    settings:
      web-allow-others: false
logging:
  level:
    org.hibernate.SQL: DEBUG           # Logs SQL queries
    org.hibernate.type.descriptor.sql: TRACE  # Logs query parameters
    org.springframework.boot.context.config: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
#security:
#  jwt:
#    secret: ${JWT_SECRET:sai0fal_vkasfbehwapofhjashofjaswfpojasfvbafophfifonfo_shjfwef}
#    issuer: ${JWT_ISSUER:api.substring.com}
#
#    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
#    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
#
#    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
#
#    cookie-secure: ${JWT_COOKIE_SECURE:true}
#    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
#    cookie-same-site: ${JWT_COOKIE_SAME_SITE:Lax}

security:
  jwt:
    secret: ${JWT_SECRET:saiofalvkasfbehwapofhjashofjaswfpojasfvbafophfifonfoshjfwefjifslajfsah}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}

#    cookie:
#      secure: ${JWT_COOKIE_SECURE:true}
#      http-only: ${JWT_COOKIE_HTTP_ONLY:true}
#      same-site: ${JWT_COOKIE_SAME_SITE:Lax}
#      refresh-token-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}


    refresh-token-cookie-name: refresh_token_cookie
    cookie-http-only: true
    cookie-secure: false   # true in prod (HTTPS)
    cookie-domain: localhost
    cookie-same-site: Lax


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Email config


# Oauth2 config


# Keyclock





