spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb   # PostgreSQL DB URL
    username: postgres                             # DB username
    password: postgres                             # DB password
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: validate               # ❗ DO NOT use update/create in prod
      show-sql: false                    # Disable SQL logs in prod

    sql:
      init:
        mode: never                      # Prevent accidental schema init


server:
  port:9082


# conifiguration database


# Email config


# Oauth2 config


# Keyclock

