server:
  port: 9081

spring:
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console
    settings:
      web-allow-others: false

  security:
    oauth2:
      client:
        registration:

          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile

          github:
            client-id: YOUR_GITHUB_CLIENT_ID
            client-secret: YOUR_GITHUB_CLIENT_SECRET
            scope:
              - user:email
        #          google:
        #            client-id: ${GOOGLE_CLIENT_ID}
        #            client-secret: ${GOOGLE_CLIENT_SECRET}
        #            scope: openid, email, profile    # openid → OIDC mode
        #          github:
        #            client-id: ${GITHUB_CLIENT_ID}
        #            client-secret: ${GITHUB_CLIENT_SECRET}
        #            scope: user:email, read:user     # GitHub doesn't support OIDC → stays OAuth2

        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

# ✅ YOUR custom JWT config (NOT under spring)
security:
  jwt:
    secret: ${JWT_SECRET:saiofalvkasfbehwapofhjashofjaswfpojasfvbafophfifonfoshjfwefjifslajfsah}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: refresh_token_cookie
    cookie-http-only: true
    cookie-secure: false
    cookie-domain: localhost
    cookie-same-site: Lax

app:
  auth:
    frontend:
      success-redirect: "http://localhost:3456/oauth-success"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger - %msg%n"

  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.boot.context.config: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

